chore: added format and linting checks to pre-commit hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,16 +1,7 @@
 #!/bin/bash
-
-# Run npm run test
-npm run test
-
-# Store the exit code of the previous command
-RESULT=$?
-
-# If tests failed, prevent the commit
-if [ $RESULT -ne 0 ]; then
-  echo "Tests failed. Commit aborted."
-  exit 1
-fi
+make format-check || { echo 'format failed. run "make format" to format your files.' ; exit 1; }
+npm run lint || { echo 'linting failed.' ; exit 1;}
+npm run test || { echo 'tests failed.' ; exit 1; }
 
 # If tests passed, allow the commit
 exit 0
